### ISSUE TITLE
composer Installation

### ISSUE THREAD

**Issue by chriza** [delahaye/dlh_geocode#10]
Hallo,

habe heute versucht mittels composer die Extension zu installieren. Habe einen Fehler erhalten, da die Extension contao-community/composer-plugin der Version 3.* voraussetzt. Diese Version existiert nicht.
![grafik](https://user-images.githubusercontent.com/1572887/39409260-366cb8e4-4be4-11e8-9721-6db9f6f922b1.png)

**Comment by delahaye** [comment]
Im kommenden Release ist das behoben/eingebaut. Danke für die Unterstützung!
